version: '3.7'
services:
  traefik:
    image: traefik:v1.7.10 # The official Traefik docker image
    command:
      - --api
      - --debug
      - --docker
      - --docker.domain=customdomain.local
      - --docker.swarmMode
      - --docker.watch
      - --docker.network=proxy
      - --docker.swarmModeRefreshSeconds=1
      - --defaultentrypoints=http
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 8080
        published: 8080
        mode: host
    networks:
      - proxy
    volumes:
      - traefik-tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    deploy:
      replicas: 1
      mode: replicated
      labels:
       - traefik.docker.network=proxy
       - traefik.port=8080
       - traefik.bakend=traefik
       - traefik.frontend.headers.browserXSSFilter=true
       - traefik.frontend.headers.frameDeny=true
       - traefik.frontend.headers.contentTypeNosniff=true
       - traefik.frontend.headers.customResponseHeaders=x-robots-tag:noindex
       - traefik.frontend.rule=Host:traefik.customDomain.local
networks:
  proxy:
    name: proxy
    driver: overlay
volumes:
  traefik-tmp: